// app/components/ol-map-popup.tsx
import React from 'react';
import { Feature } from 'ol';
import Link from 'next/link'

interface MyProps {
  features: Feature[]
};

class OLMapPopup extends React.Component<MyProps> {

  public render() {
    console.log(this.props.features.filter((_, i) => i < 5).map((feature) => feature.get('id')));
    return (
      <div className="popup-content">

        {
          this.props.features.filter((_, i) => i < 5).map((feature) => (
            <li key={feature.get('id')}>
              <Link href={`/place/${feature.get('name')}/${feature.get('id')}`} >
                <a>{feature.get('name')}</a>
              </Link>
            </li>

          ))
        }
        {
          this.props.features.length > 5 ? `...(${this.props.features.length})` : ''
        }
        <style jsx global>{`
          .popup-content {
            color: black;
          }
          a {
            color: black;
          }
        `}</style>
      </div>
    )
  };
};

export default OLMapPopup;

// app/components/OLMapPopup.vue
<template>
  <div className="popup-content">
    <li v-for="feature in features.filter((_, i) => i < 5)" :key="feature.get('id')">
      <nuxt-link :to="`/place/${feature.get('name')}/${feature.get('id')}`">
        {{ feature.get('name') }}
      </nuxt-link>
    </li>
    {{
      features.length > 5 ? `...(${features.length})` : ''
    }}
  </div>
</template>

<style>
.popup-content {
  color: black;
}
a {
  color: black;
}

</style>

<script lang="ts">
import { Component, Vue, Prop } from 'vue-property-decorator'
import { Feature } from 'ol';

@Component
export default class OLMapPopup extends Vue {

    @Prop({ type: Array, required: true })
    features!: Feature[];

    constructor() {
      super();
      console.log(this.features);
    }
}
</script>
